### ISSUE TITLE
Using AutoSizer

### ISSUE THREAD

**Issue by mbj36** [thevtm/nextjs-react-virtualized#1]
Hey @thevtm 

Thanks for this demo, i really appreciate it, Can you modify this example to use AutoSizer, I am facing problems using Autosizer

**Comment by thevtm** [comment]
Thanks man! :smile: 

The demo is supposed to be super simple, thats why I just used List.

I hope the this piece of code can help you. :crossed_fingers:  

```js
<div style={{ width: 800, height: 1000 }}>
  <AutoSizer>
    {({ height, width }) => (
      <List
        width={width}
        height={height}
        rowCount={comments.length}
        rowHeight={20}
        rowRenderer={(rowArgs) => rowRenderer(comments, rowArgs)}
      />
    )}
  </AutoSizer>
</div>
```

**Comment by mbj36** [comment]
Thanks @thevtm
